name: VoidFishing
version: ${project.version}
main: me.rxndmz.voidfishing.VoidFishing
api-version: 1.13
authors: [Rxndmz]
commands:
  Cooler:
    description: Opens the players cooler.
  Test:
    description: for testing stuff.
  FishingMerchant:
    description: opens the merchant gui
  FishingEnchanter:
    description: opens the enchanter gui
